// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfoBLmgT9lbTGcXXWUs3Y46Q6ie7VuYmQ',
    appId: '1:420133063554:web:a6ca146b5db533cc6d9d9b',
    messagingSenderId: '420133063554',
    projectId: 'whatsapp-backend-9e526',
    authDomain: 'whatsapp-backend-9e526.firebaseapp.com',
    storageBucket: 'whatsapp-backend-9e526.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoHvtVAdJuVCzXAmTprCRpjdjnUhRtdNs',
    appId: '1:420133063554:android:2a47e1ba16361c4c6d9d9b',
    messagingSenderId: '420133063554',
    projectId: 'whatsapp-backend-9e526',
    storageBucket: 'whatsapp-backend-9e526.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhrqjV3-3cpzbmm7gOV4N2i1T8CPhxREk',
    appId: '1:420133063554:ios:0e917c6cda613c026d9d9b',
    messagingSenderId: '420133063554',
    projectId: 'whatsapp-backend-9e526',
    storageBucket: 'whatsapp-backend-9e526.appspot.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhrqjV3-3cpzbmm7gOV4N2i1T8CPhxREk',
    appId: '1:420133063554:ios:e1023bb511d45a056d9d9b',
    messagingSenderId: '420133063554',
    projectId: 'whatsapp-backend-9e526',
    storageBucket: 'whatsapp-backend-9e526.appspot.com',
    iosBundleId: 'com.example.whatsapp.RunnerTests',
  );
}
